disable post-stop hook

diff --git a/hooks/post-stop b/hooks/post-stop
--- a/hooks/post-stop
+++ b/hooks/post-stop
@@ -1,13 +1,15 @@
 #!/bin/bash
 
-if [[ $exit_code -ne 0 && $(basename "$app_dir") == 'Logos' && "$app" == 'Logos.exe' ]]; then
-    # Logos/Logos.exe failed to run Logos/System/Logos.exe. Run it directly.
-    echo "Logos/Logos.exe failed to terminate correctly. Exit code: $exit_code"
-    RUN_EXE="C:/users/$USER/AppData/Local/Logos/System/Logos.exe"
-    app_dir=$(dirname "${RUN_EXE}")
-    app=$(basename "${RUN_EXE}")
-    cd "${app_dir}"
-    echo "Starting Logos/System/Logos.exe..."
-    "$WINELOADER" "$app"
-    local exit_code="$?"
-fi
+# TODO: Determine if Logos/System/Logos.exe is running.
+
+# if [[ $(basename "$app_dir") == 'Logos' && "$app" == 'Logos.exe' ]]; then
+#     # Logos/Logos.exe does not correctly start Logos/System/Logos.exe. Run it directly.
+#     echo "Logos/Logos.exe failed to terminate correctly. Exit code: $exit_code"
+#     RUN_EXE="C:/users/$USER/AppData/Local/Logos/System/Logos.exe"
+#     app_dir=$(dirname "${RUN_EXE}")
+#     app=$(basename "${RUN_EXE}")
+#     cd "${app_dir}"
+#     echo "Starting Logos/System/Logos.exe..."
+#     "$WINELOADER" "$app"
+#     local exit_code="$?"
+# fi
