add support for getting Logos version info with --version option

diff --git a/hooks/pre-start b/hooks/pre-start
--- a/hooks/pre-start
+++ b/hooks/pre-start
@@ -4,11 +4,26 @@
 #    (It's still needed before this point for wineprefix setup, though.)
 export WINEDLLOVERRIDES=$(echo $WINEDLLOVERRIDES | sed -r 's/[,;]?mscoree[,;]?//')
 
-# Get user ID and Language info for LogosIndexer.exe.
+if [[ "${ACTION_ARGS[$1]}" == '--version' ]]; then
+    # Get Logos.exe version number from wine registry and exit.
+    ver=$(grep "AssemblyVersion" "${SNAP_USER_COMMON}/.wine/user.reg" | awk -F= '{print $2}' | tr -d '"')
+    if [[ -n "$ver" ]]; then
+        echo "$ver"
+        exit 0
+    else
+        echo "ERROR: Logos.exe version number not found."
+        exit 1
+    fi
+fi
+
+# Handle alternative executables.
 if [[ $(basename "$RUN_EXE") == 'LogosIndexer.exe' ]]; then
+    # Get user ID and Language info for LogosIndexer.exe.
     LOGOS_INSTALL_DIR=$(find "$SNAP_USER_COMMON" -name Logos -type d | grep -v Faithlife)
-    export LOGOS_USER_ID=$(sed -r 's|.*"id":"([0-9a-z\.]{3,})",.*|\1|' "${LOGOS_INSTALL_DIR}/Users/UserMetadata")
-    export LOGOS_USER_LANG=$(grep 'ResourceTitleLanguage' "${SNAP_USER_COMMON}/.wine/user.reg" | awk -F= '{print $2}' | tr -d '"')
+    LOGOS_USER_ID=$(sed -r 's|.*"id":"([0-9a-z\.]{3,})",.*|\1|' "${LOGOS_INSTALL_DIR}/Users/UserMetadata")
+    LOGOS_USER_LANG=$(grep 'ResourceTitleLanguage' "${SNAP_USER_COMMON}/.wine/user.reg" | awk -F= '{print $2}' | tr -d '"')
     # export LOGOS_USER_LANG=$(grep 'ResourceTitleLanguage' "${SNAP_USER_COMMON}/.wine/user.reg" | sed -r 's|"ResourceTitleLanguage"="(.*)"|\1|')
     ACTION_ARGS=( "/user:$LOGOS_USER_ID" "/lang:$LOGOS_USER_LANG" )
+elif [[ $(basename "$RUN_EXE") == 'LogosUpdater.exe' ]]; then
+    echo "WARNING: Running LogosUpdater.exe is currently experimental."
 fi
